#!/bin/bash

Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # Whit

lsGitDir(){
  HERE=$(pwd)
  cd $1
  
  if [ "$2" == "update" ]; then
    GUP=$(git remote update > /dev/null 2>&1)
  fi

  GST=$(git status)
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  UNCLEAN=$(git status --porcelain | wc -l | tr -d " ")
  STASH=$(git stash list | wc -l | tr -d " ")
  x=$(echo $GST | grep clean) && echo -ne "$Green" || echo -ne "$Red"
  printf "%-32s $Color_Off %-32s %-3s %-3s\n" ${d:0:32} ${BRANCH:0:32} $UNCLEAN $STASH 
  cd $HERE
}

lsVcsDirs(){
  printf "%-32s $Color_Off %-26s %-9s %-3s\n" "Repo" "Branch" "Changes" "Stash Count"
  for d in $(ls $1); do
    if [ -d $d ]; then
      if [ -d $d/.git ]; then
        lsGitDir $d $2
      else
        printf "$Yellow%-32s $Color_Off %-32s %-3s %-3s\n" ${d:0:32} "n/a" "-" "-" 
      fi
    fi
  done;
}

lsVcsDirs $(pwd) $1
