#!/bin/bash

Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # Whit

lsgitDir(){
  HERE=$(pwd)
  cd $1
  GUP=$(git remote update > /dev/null 2>&1)
  GST=$(git status)
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
  UNCLEAN=$(git status --porcelain | wc -l | tr -d " ")
  STASH=$(git stash list | wc -l | tr -d " ")
  x=$(echo $GST | grep clean) && echo -ne "$Green" || echo -ne "$Red"
  echo -e "$d$Color_Off $BRANCH/$UNCLEAN/$STASH"
  cd $HERE
}

lsgitDirs(){
  for d in $(ls $1); do
    if [ -d $d ]; then
      if [ -d $d/.git ]; then
        lsgitDir $d
      else
        echo -e "$Yellow$d$Color_Off -N/A-"
      fi
    fi
  done;
}

lsgitDirs $(pwd)
